Test cases for login
ArtemPerehonchuk/rentzila-playwright-autotests pull request #2
Opened 2024-09-19 09:05 UTC by ArtemPerehonchuk

Created auto tests for authorization form on the rentzila website. Test cases: C200, C201, C202, C201, C576, C577.

2024-09-25 04:31 UTC, Vaas-d commented on .github/workflows/rentzila_login_tests.yml
> +          echo "INCORRECT_PASSWORDS_NO_UPPERCASE=${{secrets.INCORRECT_PASSWORDS_NO_UPPERCASE}}" >> .env
We do not store invalid test data as env vars. This makes no sense, this data is irrelevant and does not contain any value. 
Only sensitive data (like valid credentials) should be hidden in env vars

2024-09-25 13:47 UTC, Vaas-d requested changes
Not approved

2024-09-25 13:47 UTC, Vaas-d commented on README.md
> +This project contains end-to-end tests for the Rentzila application using Playwright. It ensures the functionality and quality of the Rentzila web application through automated browser testing.
This is a website. An application is a piece of software that can be installed onto a platform like PC, phone, etc.

2024-09-25 13:47 UTC, Vaas-d commented on .github/workflows/rentzila_login_tests.yml
> +          echo "INCORRECT_PASSWORDS_CYRILLIC=${{secrets.INCORRECT_PASSWORDS_CYRILLIC}}" >> .env
We do not store invalid test data as env vars. This makes no sense, this data is irrelevant and does not contain any value.
Only sensitive data (like valid credentials) should be hidden in env vars

2024-09-25 13:47 UTC, Vaas-d commented on README.md
> +   git clone -b tc-C212-C213-C214-C226 https://github.com/ArtemPerehonchuk/rentzila-playwright-tests.git
This branch does not exist

2024-09-25 13:47 UTC, Vaas-d commented on helpers/api.helper.ts
> +                .post('https://dev.rentzila.com.ua/api/auth/jwt/create/', {
This kind of data can be hidden in an environment variable as it as a sensitive endpoint you don't want to expose in the code

2024-09-25 13:47 UTC, Vaas-d commented on helpers/api.helper.ts
> +              .get('https://dev.rentzila.com.ua/api/backcall/', {
same as above

2024-09-25 13:47 UTC, Vaas-d commented on pages/cookie.policy.page.ts
> +        cookiePolicyTitle: this.page.getByText('Політика використання файлів cookie')
Fragile locator. Create more appropriate. Do not use text as an anchor

2024-09-25 13:47 UTC, Vaas-d commented on pages/home.page.ts
> +            loginFormErrorMsg: this.page.locator('div[data-testid="errorMessage"]')
What's the point of this? Why are you hiding your locators into an object?

2024-09-25 13:47 UTC, Vaas-d commented on pages/home.page.ts
> +    async scrollToSpicialEquipmentContainer() {
Maybe "sp**e**cial"?

2024-09-25 13:47 UTC, Vaas-d commented on pages/home.page.ts
> +    async checkFooter() {
Too broad. You are not checking the whole footer, but only it's visibility

2024-09-25 13:47 UTC, Vaas-d commented on pages/home.page.ts
> +        await expect(emailAttr).toContain('mailto:')
Bad anchor. You are not checking the actual contact email

2024-09-25 13:47 UTC, Vaas-d commented on pages/home.page.ts
> +        await this.page.waitForTimeout(3000);
Why wait for Timeout?

2024-09-25 13:47 UTC, Vaas-d commented on pages/home.page.ts
> +    async fillInput(inputName: string, inputValue: string) {
what input?

2024-09-25 13:47 UTC, Vaas-d commented on pages/home.page.ts
> +            consultationFormPhoneInput: this.page.locator('input[placeholder="Номер телефону"]'),
Fragile locators. Use more sturdy anchors

2024-09-25 13:47 UTC, Vaas-d commented on pages/privacy.policy.page.ts
> +        this.locators = {
Fragile locator

2024-09-25 13:47 UTC, Vaas-d commented on pages/products.page.ts
> +            dropdownArrow: this.page.locator('#__next > div > main > div > div > div[class*="Filters_leftContainer"] > div > div[class*="Filters_filtersWrapper"] > div[class*="Services_wrapper"] > di
Fragile locator

2024-09-25 13:47 UTC, Vaas-d commented on pages/products.page.ts
> +            constructionsCheckBox: this.page.locator('label', {hasText: 'Будівельні'}),
Fragile locator

2024-09-25 13:47 UTC, Vaas-d commented on pages/products.page.ts
> +            othersCheckBox: this.page.locator('label', {hasText: 'Інші'}),
Fragile locator

2024-09-25 13:47 UTC, Vaas-d commented on pages/terms.conditions.page.ts
> +            termsConditionsTitle: this.page.getByRole('heading', { name: 'Угода користувача' })
Fragile locator

2024-09-25 13:47 UTC, Vaas-d commented on pages/unit.page.ts
> +            unitSrvicesTitle: this.page.getByText('Послуги, які надає технічний засіб:'),
Fragile locartor

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    const homepage = new HomePage(page, apiRequestContext);
why the duplicate?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    const homepage = new HomePage(page, apiRequestContext);
why the duplicate?

2024-09-25 13:47 UTC, Vaas-d commented on pages/tenders.page.ts
> +        await expect(searchInputText).toBe('Пошук тендера за ключовими словами');
why is the expected value hard-coded in the method instead of using arguments?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await privacyPolicyPage.checkPrivacyPolicyTitle();
why is the expected value hard-coded in the method instead of using arguments?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await privacyPolicyPage.checkPrivacyPolicyTitle();
same comment for lines 41, 44, 47, 50, 53, 56.

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await expect(await homepage.checkInputError('phone')).toBe(true);
Aren't you expecting the error message to appear? why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await expect(await homepage.checkInputError('phone')).toBe(true);
Aren't you expecting the error message to appear? why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await expect(await homepage.checkInputError('phone')).toBe(false);
Aren't you expecting the error message to appear? why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await homepage.checkIncorrectPhoneErrorMsg();
why hard-coded value?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await homepage.checkSuccessSubmitConsultationMsg();
the current name does not reflect actual check

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +    const homepage = new HomePage(page);
duplicate

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +    await expect(await homepage.checkInputError('password')).toBe(true);
Aren't you expecting the error message to appear? why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +    await expect(await homepage.checkInputError('password')).toBe(true);
Aren't you expecting one error message to appear and another not? why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +    await expect(await homepage.checkInputError('password')).toBe(true);
Aren't you expecting the error message to appear? why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +    await expect(await homepage.checkInputError('password')).toBe(false);
Aren't you expecting one error message to appear and another not? why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +    const homepage = new HomePage(page);
duplicate

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +    const homepage = new HomePage(page);
duplicate

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +        await expect(await homepage.checkInputError('email')).toBe(false);
why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +        await expect(await homepage.checkInputError('password')).toBe(false);
why so complicated?

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +    ];
it is advised to declare the constants at the global level

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +        process.env.INCORRECT_PHONE_NUMBERS_WITHOUT_38 || ''
These should not be stored as env.vars. A simple data file should be enough here

2024-09-25 13:47 UTC, Vaas-d commented on pages/home.page.ts
> +            await expect(this.locators.loginFormErrorMsg).toBeVisible();
What is this?? This does not make sense. why expect it to be visible if it is already visible???

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +        await homepage.checkIncorrectInputFormat();
Overcomplicated. see the comment in the method

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +        process.env.INCORRECT_EMAILS_WITH_TWO_AT || ''
Not env.vars!!!

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +        await homepage.checkIncorrectInputFormat();
Overcomplicated. see the comment in the method

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +        await homepage.checkIncorrectInputFormat();
Overcomplicated. see the comment in the method

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.login.spec.ts
> +        process.env.INCORRECT_PASSWORDS_CYRILLIC || ''
Not env.vars!!!

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.services.spec.ts
> +    const unitPage = new UnitPage(page);
duplicate

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.services.spec.ts
> +    const unitPage = new UnitPage(page);
duplicate

2024-09-25 13:47 UTC, Vaas-d commented on pages/products.page.ts
> +    async checkCategoriesCheckboxes() {
Bad naming. You are verifying that the checkbox is checked. Checking the checkbox means actual click action on it.

2024-09-25 13:47 UTC, Vaas-d commented on tests/test.services.spec.ts
> +        await homepage.clickOnLogo();
Why your test does not end in a check?

2024-09-25 13:47 UTC, Vaas-d commented on pages/unit.page.ts
> +            await expect(this.locators.unitServicesTypesContainer).toBeVisible()
Why expect it to be visible if it is already visible???

2024-09-27 12:55 UTC, ArtemPerehonchuk commented on pages/home.page.ts
> +        await this.page.waitForTimeout(3000);
When I run test without timeout the user does not exist in the list of users that I receive in API GET request

2024-10-03 04:12 UTC, Vaas-d requested changes
Check why your tests have failed and fix the issue

2024-10-03 04:12 UTC, Vaas-d commented on pages/home.page.ts
> +    async fillInput(inputName: string, inputValue: string) {
resolved

2024-10-03 04:12 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await homepage.checkSuccessSubmitConsultationMsg();
resolved

2024-10-03 04:12 UTC, Vaas-d commented on tests/test.footer.elements.spec.ts
> +    await privacyPolicyPage.checkPrivacyPolicyTitle();
resolved

2024-10-03 04:13 UTC, Vaas-d commented
Check why your tests have failed

2024-10-05 07:24 UTC, Vaas-d approved these changes

2024-10-07 11:34 UTC, merged